// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

import Amplify from 'aws-amplify'
import config from './aws-exports'
Amplify.configure(config)


const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:de3a6fd2-40ee-4816-91f0-a4585c0a5871",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_b82nhUC7c",
    "aws_user_pools_web_client_id": "13rvc6sg76dgjobn2cn040co60",
    "oauth": {
        "domain": "projetofinal2020-local.auth.eu-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "myapp://127.0.0.1:19000/--/",
        "redirectSignOut": "myapp://127.0.0.1:19000/--/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
